/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AlbumRedactorIcons
///      fonts:
///       - asset: fonts/AlbumRedactor.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AlbumRedactorIcons {
  AlbumRedactorIcons._();

  static const _kFontFam = 'AlbumRedactorIcons';
  static const String? _kFontPkg = null;

  static const IconData text = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sticker = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
