/// Flutter icons PersonalAccountIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PersonalAccountIcons
///      fonts:
///       - asset: fonts/PersonalAccountIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PersonalAccountIcons {
  PersonalAccountIcons._();

  static const _kFontFam = 'PersonalAccountIcons';
  static const String? _kFontPkg = null;

  static const IconData changePassword = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData confidentiality = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profileRedactor = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rightArrow = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData avatarPlaceholder = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData children = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
